# frozen_string_literal: true

# db/migrate/20231027000000_create_items.rb
#
# This migration file defines the `items` table in the database.
# It is generated by `rails generate model Item name:string description:text`.
class CreateItems < ActiveRecord::Migration[7.1]
  # The `change` method is executed when running `rails db:migrate`.
  # It automatically knows how to reverse the migration when running `rails db:rollback`.
  def change
    # Creates a table named `items`.
    # `t.string :name` adds a string column named `name`.
    # `t.text :description` adds a text column named `description`.
    # `t.timestamps` adds `created_at` and `updated_at` datetime columns,
    # which ActiveRecord automatically manages.
    create_table :items do |t|
      t.string :name
      t.text :description

      t.timestamps
    end
  end
end
